spring:
  profiles:
    active: dev
    group:
      local:
        - localdb
        - s3
        - jwt-local
        - port
      dev:
        - devdb
        - s3
        - jwt-dev
        - port
  pid:
    file: /home/ubuntu/swulab/eatswunee/eatswunee.pid

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false




