spring:
  profiles:
    active: dev
    group:
      local:
        - localdb
        - s3
        - jwt-local
      dev:
        - devdb
        - s3
        - jwt-dev
  pid:
    file: /home/ubuntu/swulab/eatswunee/eatswunee.pid




