spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      format_sql: true
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

sql:
  init:
    mode: always
